GET http://localhost:3000/users

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "user_register": "Jim",
    "pass_register": "lindsay",
    "email_register": "shit@fart.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Jim",
    "password": "lindsay"
}
